package org.breeze.entity;

public class Resources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.id
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.url
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.priority
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.type
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.name
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.id
     *
     * @return the value of resources.id
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.id
     *
     * @param id the value for resources.id
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.url
     *
     * @return the value of resources.url
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.url
     *
     * @param url the value for resources.url
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.priority
     *
     * @return the value of resources.priority
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.priority
     *
     * @param priority the value for resources.priority
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.type
     *
     * @return the value of resources.type
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.type
     *
     * @param type the value for resources.type
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.name
     *
     * @return the value of resources.name
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.name
     *
     * @param name the value for resources.name
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public void setName(String name) {
        this.name = name;
    }
}