package org.breeze.entity;

public class RolesResources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles_resources.rrId
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    private Integer rrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles_resources.rsid
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    private Integer rsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles_resources.rid
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    private Integer rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles_resources.rrId
     *
     * @return the value of roles_resources.rrId
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public Integer getRrid() {
        return rrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles_resources.rrId
     *
     * @param rrid the value for roles_resources.rrId
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public void setRrid(Integer rrid) {
        this.rrid = rrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles_resources.rsid
     *
     * @return the value of roles_resources.rsid
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public Integer getRsid() {
        return rsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles_resources.rsid
     *
     * @param rsid the value for roles_resources.rsid
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public void setRsid(Integer rsid) {
        this.rsid = rsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles_resources.rid
     *
     * @return the value of roles_resources.rid
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles_resources.rid
     *
     * @param rid the value for roles_resources.rid
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }
}