package org.breeze.entity;

public class UsersRoles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_roles.urId
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    private Integer urid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_roles.uid
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_roles.rid
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    private Integer rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_roles.urId
     *
     * @return the value of users_roles.urId
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public Integer getUrid() {
        return urid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_roles.urId
     *
     * @param urid the value for users_roles.urId
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public void setUrid(Integer urid) {
        this.urid = urid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_roles.uid
     *
     * @return the value of users_roles.uid
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_roles.uid
     *
     * @param uid the value for users_roles.uid
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_roles.rid
     *
     * @return the value of users_roles.rid
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_roles.rid
     *
     * @param rid the value for users_roles.rid
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }
}