package org.breeze.entity;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.enable
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    private Integer enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.account
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    private String account;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.enable
     *
     * @return the value of users.enable
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.enable
     *
     * @param enable the value for users.enable
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.account
     *
     * @return the value of users.account
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.account
     *
     * @param account the value for users.account
     *
     * @mbggenerated Tue Aug 21 12:32:28 CST 2012
     */
    public void setAccount(String account) {
        this.account = account;
    }
}