package org.breeze.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.breeze.entity.RolesResources;
import org.breeze.entity.RolesResourcesExample;

public interface RolesResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_resources
     *
     * @mbggenerated Sat Aug 11 10:36:18 CST 2012
     */
    int countByExample(RolesResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_resources
     *
     * @mbggenerated Sat Aug 11 10:36:18 CST 2012
     */
    int deleteByExample(RolesResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_resources
     *
     * @mbggenerated Sat Aug 11 10:36:18 CST 2012
     */
    int deleteByPrimaryKey(Integer rrid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_resources
     *
     * @mbggenerated Sat Aug 11 10:36:18 CST 2012
     */
    int insert(RolesResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_resources
     *
     * @mbggenerated Sat Aug 11 10:36:18 CST 2012
     */
    int insertSelective(RolesResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_resources
     *
     * @mbggenerated Sat Aug 11 10:36:18 CST 2012
     */
    List<RolesResources> selectByExample(RolesResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_resources
     *
     * @mbggenerated Sat Aug 11 10:36:18 CST 2012
     */
    RolesResources selectByPrimaryKey(Integer rrid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_resources
     *
     * @mbggenerated Sat Aug 11 10:36:18 CST 2012
     */
    int updateByExampleSelective(@Param("record") RolesResources record, @Param("example") RolesResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_resources
     *
     * @mbggenerated Sat Aug 11 10:36:18 CST 2012
     */
    int updateByExample(@Param("record") RolesResources record, @Param("example") RolesResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_resources
     *
     * @mbggenerated Sat Aug 11 10:36:18 CST 2012
     */
    int updateByPrimaryKeySelective(RolesResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_resources
     *
     * @mbggenerated Sat Aug 11 10:36:18 CST 2012
     */
    int updateByPrimaryKey(RolesResources record);
}